# -*- coding: utf-8 -*-
"""PUBH6859_Assignment4_Boto3_CREATE.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GrHtl4S4lIBmA1bmL154LUaJzZaKlBSM
"""

# Install boto3
!pip install boto3

# Load packages
import boto3

# Create S3 Bucket
s3 = boto3.resource('s3', aws_access_key_id = 'aws_access_key_id',
                          aws_secret_access_key= 'aws_secret_access_key')

s3.create_bucket(Bucket='pubh6859assignment4boto3')

# Print name to confirm created Bucket
for bucket in s3.buckets.all():
    print(bucket.name)

# Create EC2 Instance
ec2 = boto3.resource('ec2','us-east-1',
                            aws_access_key_id = 'aws_access_key_id',
                            aws_secret_access_key= 'aws_secret_access_key')

response = ec2.create_instances(ImageId='ami-04e5276ebb8451442', MinCount=1, MaxCount=1)

# Print ID of instance created
instance_id = response[0].instance_id
print(instance_id)