# -*- coding: utf-8 -*-
"""PUBH6859_Assignment4_Boto3_DELETE.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1chreLQ3FX27YsvXsa1Hbuc_6nPlYoSeH
"""

# Install boto3
!pip install boto3

# Load packages
import boto3

# Delete S3 Bucket
s3 = boto3.resource('s3', aws_access_key_id = 'aws_access_key_id',
                          aws_secret_access_key= 'aws_secret_access_key')

s3.Bucket('pubh6859assignment4boto3').delete()

# Confirm deletion of S3 Bucket
for bucket in s3.buckets.all():
    print(bucket.name)

# Delete EC2 Instance
ec2_client = boto3.client('ec2','us-east-1',
                            aws_access_key_id = 'aws_access_key_id',
                            aws_secret_access_key= 'aws_secret_access_key')

# Obtained from first script
instance_id = "i-0ace771fb0e2e8af8"

response = ec2_client.terminate_instances(InstanceIds=[instance_id])